version: "3"
services:
  backend:
    build: 
      context: .
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    links:
      - db
    volumes:
      - ./backend:/app

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    expose:
      - '3306'
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
      - db:/var/lib/mysql

volumes:
  db:
    driver: local
